name: Build kernel deb packages

on:
  workflow_dispatch:

jobs:
  build:
    name: Build kernel
    runs-on: ubuntu-latest
    container: debian:buster
    steps:
      - uses: actions/checkout@v3
      - run: |
          git clone -q --single-branch --depth=1 --branch=meson64-6.6 https://github.com/devmfc/linux.git

      - name: Build
        run: bash build_action.sh

      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ${{ github.workspace }}/artifact/
